### ISSUE TITLE
std::allocator<> with VS 15.5 and /std:c++latest

### ISSUE THREAD

**Issue by matbech** [boostorg/iostreams#43]
The VS 15.5 compiler (/std:c++latest ) complains about zlib.hpp because of the deprecated std::allocator<>

``
error C4996: 'std::allocator<char>::rebind<char>::other': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
``

File: zlib.hpp
```
template<typename Alloc>
struct zlib_allocator_traits {
#ifndef BOOST_NO_STD_ALLOCATOR
    typedef typename Alloc::template rebind<char>::other type;
...

template<typename Alloc = std::allocator<char> >
class zlib_compressor_impl : public zlib_base, public zlib_allocator<Alloc> {

etc 
```

**Comment by eldiener** [comment]
The problem appears to be knowing in the code when msvc-14.1 is being used and /std:c++latest is being used as a compiler option. I can use Boost.Config to determine that msvc-14.1 is being used but I do not see how I am to determine that /std:c++latest is being used by the compiler.

**Comment by matbech** [comment]
boost config requires additional macros for C++17 like the ones here:
http://www.boost.org/doc/libs/1_65_1/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_c__17_features_not_supported

For example for std::allocator_traits:
BOOST_NO_CXX17_STD_ALLOCATOR_TRAITS

Then this can be checked in the libs like iostreams.

**Comment by eldiener** [comment]
It looks like for C++11 on up I should be able to replace:

`typedef typename Alloc::template rebind<char>::other type;`

with

`typedef typename std::allocator_traits<Alloc>::template rebind_alloc<char> type;`

**Comment by eldiener** [comment]
Thanks for opening this issue. I have posted a fix in the 'develop' branch of iostreams. Feel free to test it out as I have done.

**Comment by matbech** [comment]
Thank you. There are a few other places that need some care:
https://github.com/boostorg/iostreams/search?utf8=%E2%9C%93&q=std%3A%3Aallocator&type=
e.g.
https://github.com/boostorg/iostreams/blob/develop/include/boost/iostreams/detail/buffer.hpp#L42
https://github.com/boostorg/iostreams/blob/develop/include/boost/iostreams/filter/lzma.hpp#L115

**Comment by eldiener** [comment]
I pushed to develop changes for the other situations where BOOST_NO_STD_ALLOCATOR is being checked.
